version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # Assuming the GPU ID is 0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    volumes:
      - ./open-webui:/app/backend/data
    network_mode: host
    restart: unless-stopped
    depends_on:
      - ollama

